export { default as CourseHero } from './Hero'
export { default as CourseAbout } from './About'
export { default as CourseDetails } from './Details'
export { default as CourseMentors } from './Mentors'
export { default as CourseStudents } from './Students'
export { default as CourseApplicationProcess } from './ApplicationProcess'
export { default as CourseFAQs } from './Faqs'
export { CourseArticles } from './CourseArticles'

// New conversion-focused components (Jan 2026)
export { default as IntakeBanner } from './IntakeBanner'
export { default as PaymentCalculator } from './PaymentCalculator'
export { default as GraduateOutcomes } from './GraduateOutcomes'
export { default as CertificateUpgrade } from './CertificateUpgrade'
export { default as ProgramComparison } from './ProgramComparison'
